# This is a basic workflow that is manually triggered

name: Test JDK Latest Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Install the latest Java, Compile HelloWorld.java into a class, and run the class.
    steps:
      - uses: actions/checkout@v2
      - name: Get GCC
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get purge build-essential
          sudo apt-get install build-essential
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true
      - name: Compile and Run HelloWorld
        run: |
          javac HelloWorld.java
          java HelloWorld
