name: Test JDKs Latest Version
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  JDK-Test:
    runs-on: ubuntu-20.04
    name: Install Java and run the java class.
    steps:
      - uses: actions/checkout@v2
      - name: Get GCC
        # Runs sudo apt-get to update dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get purge build-essential
          sudo apt-get install build-essential
      - name: Setup Java
        # Sets up the JDK from actions/setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true
      - name: Run HelloWorld
        # Compiles the .java file into a class, then runs the class.
        run: |
          javac HelloWorld.java
          java HelloWorld
